=== jssdocente/LMSGI-2122/B1/T2/ejemplos/XSD/basicos/4.vehiculos/vehiculo_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Escribir un XML Schema para el siguiente documento XML, e incluir los cambios necesarios en el mismo para referenciar al esquema creado. Se debe cumplir también lo siguiente: 
 
* Los elementos “vehículo”, “nombre” y “modificacion” deben aparecer mínimo una vez, 
  y el máximo no está limitado. El resto de los elementos deben aparecer 1 vez. 
* Todos los elementos que aparecen en el documento instancia de abajo son obligatorios
   y deben aparecer siempre en el mismo orden. 
* Los elementos que contienen información de fecha son todos de tipo cadena.
  -->
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
  <xs:element name = "vehiculos">
    <xs:complexType>
      <xs:sequence>

        <xs:element name = "vehiculo" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name = "nombre" type = "xs:string" maxOccurs = "unbounded"/>
              <xs:element name = "modelo" type = "xs:string"/>

              <xs:element name = "fabricacion">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="inicio">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dia" type="xs:string"/>
                          <xs:element name="mes" type="xs:string"/>
                          <xs:element name="anyo" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="fin">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="dia" type="xs:string"/>
                          <xs:element name="mes" type="xs:string"/>
                          <xs:element name="anyo" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                  </xs:sequence>
                </xs:complexType>
              </xs:element>

              <xs:element name = "modificaciones">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name = "modificacion" type = "xs:string" maxOccurs = "unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>

            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== jssdocente/LMSGI-2122/B1/T2/ejemplos/XSD/basicos/4.vehiculos/vehiculo_1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<vehiculos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./vehiculo_1.xsd">
  <vehiculo>
    <nombre>Count Zero</nombre>
    <modelo>Series, I, 80''</modelo>
    <fabricacion>
      <inicio>
        <dia>21</dia>
        <mes>July</mes>
        <anyo>1949</anyo>
      </inicio>
      <fin>
        <dia>21</dia>
        <mes>July</mes>
        <anyo>1949</anyo>
      </fin>
    </fabricacion>
    <modificaciones>
      <modificacion>Change Engine</modificacion>
      <modificacion>Change Engine</modificacion>
      <modificacion>Change Engine</modificacion>
      <modificacion>Change Engine</modificacion>
      <modificacion>Change Engine</modificacion>
    </modificaciones>
  </vehiculo>
</vehiculos>
